version: "3"

services:
  luxai_mmsrv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7778:7778"
    environment:
      ADDR: "0.0.0.0"
      PORT: "7778"
    restart: always
