version: "3"

services:
  luxai_mmsrv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:7777:7777"
    environment:
      ADDR: "0.0.0.0"
      PORT: "7777"
    restart: always
